version: '3.8'

services:
  web:
    container_name: "backend-estimate"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app/.env
    ports:
      - 8000:8000
    restart: always
    volumes:
      - .:/app