"""first migration

Revision ID: 31cd2e85f72e
Revises: 
Create Date: 2024-02-15 17:28:43.350115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31cd2e85f72e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_predicted_conclusion', sa.DateTime(), nullable=False),
    sa.Column('date_conclusion', sa.DateTime(), nullable=True),
    sa.Column('developers_quantity', sa.Integer(), nullable=True),
    sa.Column('develop_hours', sa.Integer(), nullable=True),
    sa.Column('stack', sa.String(length=100), nullable=False),
    sa.Column('xp_level', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_field', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('experience', sa.String(length=100), nullable=True),
    sa.Column('date_register', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.Integer(), nullable=False),
    sa.Column('week_hours', sa.Float(), nullable=True),
    sa.Column('current_job', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('expert', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_predicted_conclusion', sa.DateTime(), nullable=False),
    sa.Column('date_conclusion', sa.DateTime(), nullable=True),
    sa.Column('develop_hours', sa.Float(), nullable=True),
    sa.Column('develop_predict_hours', sa.Float(), nullable=True),
    sa.Column('problems', sa.String(length=200), nullable=True),
    sa.Column('keywords', sa.String(length=100), nullable=True),
    sa.Column('requirements', sa.String(length=300), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('libs', sa.String(length=300), nullable=True),
    sa.Column('sugestions', sa.String(length=300), nullable=True),
    sa.Column('task_action', sa.String(length=300), nullable=True),
    sa.Column('component_action', sa.String(length=300), nullable=True),
    sa.Column('seniority', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('usuario_projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valuation', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_id'), 'valuations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuations_id'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_table('usuario_projeto')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
