"""migration

Revision ID: 5d13b81ff37d
Revises: 1cecc72ff0c1
Create Date: 2024-01-25 18:21:47.246223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d13b81ff37d'
down_revision: Union[str, None] = '1cecc72ff0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_predicted_conclusion', sa.DateTime(), nullable=False),
    sa.Column('date_conclusion', sa.DateTime(), nullable=True),
    sa.Column('develop_hours', sa.Float(), nullable=True),
    sa.Column('problems', sa.String(length=200), nullable=True),
    sa.Column('keywords', sa.String(length=100), nullable=True),
    sa.Column('requirements', sa.String(length=300), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('libs', sa.String(length=300), nullable=True),
    sa.Column('sugestions', sa.String(length=300), nullable=True),
    sa.Column('action', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('user_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_projects_id'), 'user_projects', ['id'], unique=False)
    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valuation', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_id'), 'valuations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuations_id'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_index(op.f('ix_user_projects_id'), table_name='user_projects')
    op.drop_table('user_projects')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
