"""task user valuation relation

Revision ID: dd9847fe80b7
Revises: 39b92ee5849a
Create Date: 2024-01-26 16:48:30.872753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9847fe80b7'
down_revision: Union[str, None] = '39b92ee5849a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'valuations', 'projects', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'valuations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'valuations', type_='foreignkey')
    op.drop_constraint(None, 'valuations', type_='foreignkey')
    # ### end Alembic commands ###
