"""task valuation relation

Revision ID: f2147832db17
Revises: dd9847fe80b7
Create Date: 2024-01-26 16:49:45.136388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2147832db17'
down_revision: Union[str, None] = 'dd9847fe80b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('valuations_ibfk_1', 'valuations', type_='foreignkey')
    op.create_foreign_key(None, 'valuations', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'valuations', type_='foreignkey')
    op.create_foreign_key('valuations_ibfk_1', 'valuations', 'projects', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
