version: "3.3"

services:
  web:
    container_name: "backend-estimate"
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: estimate_db
    ports:
      - "3307:3306"
