version: '3.8'

services:
  web:
    container_name: "backend-estimate"
    build: .
    depends_on: 
      - mysql
    command: sh -c "uvicorn main:app --reload --port 8000"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: estimate_db
    ports:
      - "3307:3306"